# //  Created by Qazi Ammar Arshad on 30/06/2020.
# //  Copyright © 2020 Qazi Ammar Arshad. All rights reserved.
"""
This code draw the annotation file on the images that are generated by merging the label box and code annotation files
togather.
"""
from custom_classes import path
import json
import cv2
import os

# folder base path.

folder_base_path = path.dataset_path + "Shalamar_Captured_Malaria/"
final_annotation_path = folder_base_path + "final_annotaion.json"
save_cells_path = folder_base_path + "individual_cells/"
# read json file
with open(final_annotation_path) as annotation_path:
    final_annotaion = json.load(annotation_path)

json_dictionary = []

# %%

for image_annotation in final_annotaion:
    # we are testing on subset of images so first we check if images
    img_name = image_annotation["image_name"]
    img_path = folder_base_path + "images/" + img_name
    if not os.path.isfile(img_path):
        print("No file Found")
        continue
    print(img_name)
    # load image for testing either annotation are combining in correct way
    img = cv2.imread(img_path)
    image = img.copy()
    json_object = []
    counter = 1
    for object in image_annotation["objects"]:
        category = object["type"]
        bbox = object["bbox"]
        x = int(bbox['x'])
        y = int(bbox['y'])
        h = int(bbox['h'])
        w = int(bbox['w'])
        if category == 'red blood cell':
            cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)
        else:
            cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 2)
        roi = image[y:y + h, x:x + w]
        cell_name = img_name[:-4] + "_" + str(counter) + ".JPG"

        cv2.imwrite(save_cells_path + category + '/' + cell_name, roi)
        counter += 1

    #     save image annotated image
    cv2.imwrite(folder_base_path + "final_images/" + img_name, img)
    #   save cell location in json file.
    # json_dictionary.append({
    #     "image_name": img_name,
    #     "objects": json_object
    # })

# save cell json file.
# save_json_image_path = folder_base_path + "rbc_location/" + "single_cell_location.json"
# with open(save_json_image_path, "w") as outfile:
#     json.dump(json_dictionary, outfile)
