# //  Created by Qazi Ammar Arshad on 18/06/2020.
# //  Copyright © 2020 Qazi Ammar Arshad. All rights reserved.
"""
This file contains the code that first draw annotations on images by this code and save annotation into a JSON file.
Then we upload this annotated image on labelbox and draw box on the cell that are not detected and draw an other box
on the annotated box generated by code which is wrong. after this we download annotated file from the labelbox and
the compare with the annotation file generated by the this code. if 2 boxes overlap on each other then we removed these
boxes from both annotation files.
"""

from custom_classes import path, cv_iml
from RedBloodCell_Segmentation.seg_dr_waqas_watershed_microscope_single_image import get_detected_segmentaion
import cv2
import json

# base path of folder where images and annotaion are saved.
folder_base_path = path.dataset_path + "IML_dataset/new_microcsope/p.v/"
# path of folder where all images are save.
original_images_path = folder_base_path + "100X_crop/"
# save annotaion path.
save_annotation_path = folder_base_path + "code_annotation_file/"
save_images_path = folder_base_path + "annotated_images/"

all_images_name = path.read_all_files_name_from(original_images_path, '.JPG')

# %%

for image_name in all_images_name:
    # reading images form the folder
    # img = cv2.imread(original_images_path + image_name)
    annotated_img, _, json_object = get_detected_segmentaion(original_images_path + image_name)

    cv2.imwrite(save_images_path + image_name, annotated_img)

    save_annotation_json = save_annotation_path + image_name.split('.')[0] + ".json"
    with open(save_annotation_json, "a") as outfile:
        json.dump(json_object, outfile)
